version: "3"

services:
    # nginx:
    #   image: nginx:1.15-alpine
    #   ports:
    #     - "80:80"
    #     - "443:443"
    #   volumes:
    #     - ./data/nginx:/etc/nginx/conf.d
    #     - ./data/certbot/conf:/etc/letsencrypt
    #     - ./data/certbot/www:/var/www/certbot
    #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    # certbot:
    #   image: certbot/certbot
    #   volumes:
    #     - ./data/certbot/conf:/etc/letsencrypt
    #     - ./data/certbot/www:/var/www/certbot
    #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    client:
      build: ./client
      container_name: client
      image: supreme_vibez:client
      restart: always
      ports:
        - 80:80
      volumes:
        - ./client:/client
        - /client/node_modules
      links:
        - backend
        - chat
    backend:
      container_name: express-mongo
      build: ./backend
      image: supreme_vibez:backend
      restart: always
      ports:
        - 5001:5001
      volumes:
        - ./backend:/backend
        - /backend/node_modules
      links:
        - mongo
    chat:
      build: ./chat-node
      image: supreme_vibez:chat
      container_name: chat-service
      restart: always
      ports:
        - 4000:4000
      volumes:
        - ./chat-node:/chat-node
        - /chat-node/node_modules
      links:
        - mongo
    mongo:
      container_name: mongo
      image: mongo
      ports:
        - "27017:27017"

    #     image: mhart/alpine-node:8.11.4
    #     restart: always
    #     ports:
    #         - "5000:5000"
    #     volumes:
    #         - ./backend:/backend
    #         - /backend/node_modules
    #     # depends_on:
    #     #     - mongodb
    #     networks:
    #         - webappnetwork
    
    #     image: mhart/alpine-node:8.11.4
    #     restart: always
    #     ports:
    #       - "4000:4000"
    #     volumes:
    #       - ./chat-node:/chat-node
    #       - /chat-node/node_modules
    #     # depends_on:
    #     #   - mongodb
    #     networks:
    #         - webappnetwork
    # mongodb:
    #     image: mongo
    #     restart: always
    #     container_name: mongodb
    #     ports:
    #         - 27017:27017
